Problem 2.9  For the spring assemblages shown in Figure P2-8 through P2-16, determine the nodal displacements, the forces in each element, and the reactions. Use the direct stiffness method for all problems.

$$
\left\{\begin{array}{l}
F_{1 x} \\
F_{2 x} \\
F_{3 x} \\
F_{4 x}
\end{array}\right\}
=\left[\begin{array}{cccc}
k & -k & 0 & 0 \\
-k & 2 k & -k & 0 \\
0 & -k & 2 k & -k \\
0 & 0 & -k & k
\end{array}\right]\left\{\begin{array}{l}
u_{1 x}  \\
u_{2 x} \\
u_{3 x} \\
u_{4 x}
\end{array}\right\}
$$

Since $u_{1x}=0$, we get 
$$
\left\{\begin{array}{l}
F_{2 x} \\
F_{3 x} \\
F_{4 x}
\end{array}\right\}=\left[\begin{array}{ccc}
2 k & -k & 0 \\
-k & 2 k & -2k \\
0 & -k & k
\end{array}\right]\left\{\begin{array}{l}
u_{2 x} \\
u_{3 x} \\
u_{4 x}
\end{array}\right\}
$$

In [9]:
# inverse matrix calculation using numpy

import numpy as np 

stiff_mat = np.array([[2,-1, 0],
              [-1,2,-1],
              [0,-1,1]]) 
inv_stiff_mat = np.linalg.inv(x) 
print(y)

[[1. 1. 1.]
 [1. 2. 2.]
 [1. 2. 3.]]


$$
\left\{\begin{array}{l}
u_{2 x} \\
u_{3 x} \\
u_{4 x}
\end{array}\right\}=\left[\begin{array}{ll}
1 & 1 & 1 \\
1 & 2 & 2 \\
1 & 2 & 3
\end{array}\right]\left\{\begin{array}{l}
F_{2 x} \\
F_{3 x} \\
F_{4 x}
\end{array}\right\}
$$

$$
\begin{equation}
u_{2 x}=\frac{1}{k}\left(F_{2 x}+F_{3 x}+F_{4 x}\right) \\
u_{3 x}=\frac{1}{k}\left(F_{2 x}+2 F_{3 x}+2 F_{4 x}\right) \\
u_{4 x}=\frac{1}{k}\left(F_{2 x}+2 F_{3 x}+3 F_{4 x}\right)
\end{equation}
$$

Sustituting the given conditions we get, 

$$
u_{2 x}=75mm\\
u_{3 x}=175mm\\
u_{4 x}=275mm
$$

$$
f_{1 x}^{(1)}=k u_{1 x}-k u_{2 x} =-15000N \\
f_{2 x}^{(1)}=-k u_{1 x}+k u_{2 x} =15000N \\
f_{2 x}^{(2)}=k u_{2 x}-k u_{3 x} = -20000N \\
f_{3 x}^{(2)}=-k x_{2 x}+k u_{3 x} = 20000N \\
f_{3 x}^{(3)}=k u_{3 x}-k u_{4 x} = -20000N \\
f_{4 x}^{(3)}=-  k u_{3 x}+k u_{4 x} = 20000N 
$$

$$
F_{1x} = f_{1 x}^{(1)} = -15000N
$$